export const SET_MOVIES = "SET_MOVIES"

export const SET_IS_LOADING = "SET_IS_LOADING"

export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES"

export const SET_CURRENT_YEAR =  "SET_CURRENT_YEAR"

export const SET_GENRES = "SET_GENRES"

export const SET_SELECTED_GENRE = "SET_SELECTED_GENRE"

export const SET_GENRE_PAGE = "SET_GENRE_PAGE"

export const SET_ALL_GENRE = "SET_ALL_GENRE"

export const OPEN_SEARCH_MODAL = "OPEN_SEARCH_MODAL"

export const SET_SEARCH_MOVIES = "SET_SEARCH_MOVIES"

export const SET_SEARCH_PARAM = "SET_SEARCH_PARAM"

export const REMOVE_SEARCH_MOVIES = "REMOVE_SEARCH_MOVIES"

export const UPDATE_SEARCH_PAGE = "UPDATE_SEARCH_PAGE"